### ISSUE TITLE
Grouped item sidebar

### ISSUE THREAD

**Issue by benalleng** [thunderbiscuit/opcode-explained#16]
I am wondering if there is any desire for a grouped item sidebar organized by type?

made a quick preview edited in the DOM

https://github.com/user-attachments/assets/87e34d56-2d21-4900-b427-a82a34a047a7

**Comment by thunderbiscuit** [comment]
Yeah I'm not opposed to it, but I'd need a really good reason (and other folks who also think it's a better way to display them). The groupings was basically my initial beef with pages like https://en.bitcoin.it/wiki/Script. The groupings need to break the single list continuity from 0-255, and then you're left wondering a bunch of stuff, for example:

- Do all possible bytes correspond to an opcode? (yes, but you don't know from the page alone)
- Why are some opcodes missing from the page?
- Why are they grouped conceptually but not in their ordering?

Moreover:
1. you have a lot of opcodes that might belong in a few _different_ groupings (I'd need to confirm this but it's very likely)
2. You always end up with a group that's like "misc" because they don't fit anywhere else.

The current approach is conceptually cleaner because it resembles a dictionary (might be better name for it than the one I currently use, _encyclopedia_?) where all words are listed in no particular order, one at a time. Easy to find them, you don't need to have prior knowledge of what category they belong to.

You do, however, make me wonder if a page that collects the opcodes in conceptual categories would be useful (in fact I'm certain it would). This would help also break the feeling of "wow there is so much to learn", when in fact it's only a few different concepts that you need to grapple with.

Anyway happy to hear other people's thoughts on this! Take my opinion with a grain of salt,, and thanks for caring about the website and taking a critical look at it!

**Comment by benalleng** [comment]
Ahh, I didn't even think about them being ordered by their opcode number! I just saw `op_0` and `op_pushbytes_1` after one another and said... huh but i guess they are 0 and 1 _satohsi whyy_

Perhaps these categories are better to remain in the script pages where they may not be individually talked about but can easily be all listed by category like they sort-of already are in the Push Operators page https://opcodeexplained.com/script/push.html

**Comment by benalleng** [comment]
Perhaps the list could be made slightly more clear on __why__ they are ordered that way? 
numbers on the side? heading? not sure, just something to think about. 

Going to close this for now as I think this particular iteration isn't it

**Comment by vostrnad** [comment]
> Perhaps the list could be made slightly more clear on why they are ordered that way?

The opcodes in the sidebar were numbered before e0ab775d166408f6333aa64bb8fdf30421cedf97, personally I liked it more that way.

**Comment by thunderbiscuit** [comment]
Oh interesting @vostrnad! I wasn't sure about removing them when I did, and now I'm reconsidering! I'll opened a new issue for it: #17.
